### ISSUE TITLE
[FRONT] automatisation validité HTML + passer en DEV dependencies

### ISSUE THREAD

**Issue by suli-octo** [DNUM-SocialGouv/1j1s-front#1155]
## Contexte
Lighthouse ne fait pas de validation HTML, nous avons plusieurs erreurs HTML qui n'ont pas été détectées concernant la structure HTML.

## Solution possible : 
utilisation de validator/validator (https://github.com/validator/validator) 

## Conséquence 
HAPPY

**Comment by gmoocto** [comment]
Outil à creuser : nu ?
