### ISSUE TITLE
[FRONT] Investiguer le package-lock.json qui se re-génère à chaque install

### ISSUE THREAD

**Issue by Mintoo200** [DNUM-SocialGouv/1j1s-front#1337]
## Contexte
à chaque `npm install`, le package-lock.json se re-génère.

## Solutions Envisagées
🤷 

## Conséquences
plus besoin de restore le packa-lock.json à chaque `npm install`, plus de risque de le commit involontairement, ...

**Comment by suli-octo** [comment]
ça semble rétabli, clôturée
