### ISSUE TITLE
[FRONT] - Scinder le Strapi repository

### ISSUE THREAD

**Issue by juliebrunetto83** [DNUM-SocialGouv/1j1s-front#1386]
## Contexte
A l'heure actuelle, les appels à notre CMS se font depuis le strapi.repository.ts, ce qui engendre un fichier de plus de 240 lignes, de même pour les tests. 

## Solutions Envisagées
Scinder le Strapi repository en plusieurs repositories en fonction du contexte 

## Conséquences
Avoir un code et des tests plus lisible

## Recette
Faire une validation de non-régression

**Comment by juliebrunetto83** [comment]
Métier [-]

**Comment by suli-octo** [comment]
@juliebrunetto83 en cours de réfacto pour les formations initiales détails, besoin de pairer à la prochaine séance jardinage 🙏
