### ISSUE TITLE
[FRONT] -  Page Avantages Mobilisation revoir la sémantique HTML

### ISSUE THREAD

**Issue by olivocto** [DNUM-SocialGouv/1j1s-front#856]
## Contexte:
Problème de sémantique sur la page

## Solutions envisagées:
Modifier les balises articles mal utlisées -> utiliser 'section' à la place
Se passer de la librairie Marked

## Conséquences:
Respecter les standards HTML du W3C

**Comment by suli-octo** [comment]
La librairie Marked a été déjà supprimée
