### ISSUE TITLE
[FRONT] - Ajouter un polyfill pour supporter la modale

### ISSUE THREAD

**Issue by Drastal** [DNUM-SocialGouv/1j1s-front#907]
## Contexte
L'élément dialog est actuellement utilisé dans le composant Modal. Cet élément relativement récent a un support limité, cela nous prive de certains utilisateurs, notamment d'utlisateurs sous Safari iOS.

## Solutions Envisagées
Voir si ce polyfill pourrait convenir : https://github.com/GoogleChrome/dialog-polyfill

## Conséquences
ça fait des Chocapic

**Comment by juliebrunetto83** [comment]
Il y a un problème d'import à cause du SSR avec dialog-polyfill => https://github.com/GoogleChrome/dialog-polyfill/issues/230

Solution => Trouver une alternative à dialog-polyfill ou implémenter nous même la modale.

**Comment by Mintoo200** [comment]
En fait plus besoin : https://caniuse.com/mdn-html_elements_dialog

C'est bien quand on attend et que les choses se font toutes seules 🙃
